name: Build Release
runs:
  using: composite
  steps:
    - name: Copy Release Train Settings
      shell: bash
      run: |
        if [ ! -f release-train-settings.xml ]; then
          cp "${{ github.action_path }}/../release-train-settings.xml" release-train-settings.xml
        fi
    - name: Build Release
      shell: bash
      run:  ./mvnw --no-transfer-progress --batch-mode --settings release-train-settings.xml clean deploy --activate-profiles releaseTrain -DaltDeploymentRepository="release-train::default::file://$(pwd)/deployment-repository" -DskipTests